server:
  port: 11000
  contextPath: /uaa

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

spring:
  rabbitmq:
    addresses: rabbitmq:5673
    username: admin
    password: admin
  couchbase:
    hosts: db1,db2
    bucket: gj-auth
    password:

hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true

security:
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**,/resources/**

token:
  access:
    life: 3600
  refresh:
    life: 3600
